name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Paso para instalar dependencias
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Ajusta a la versión que estés usando

      - name: Install dependencies
        run: npm install

      - name: Update dependencies
        run: npm update  # Esto asegura que todas las dependencias estén actualizadas

      # Paso para hacer build
      - name: Build project
        run: npm run build

      # Paso para desplegar a Firebase
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ESCOM_PHONE_GROUPS }}'
          channelId: live
          projectId: escom-phone-groups
